/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary": "#4c56af",
        "error": "#ba1a1a",
        "outline-variant": "#e4beb4",
        "primary-fixed": "#ffdbd1",
        "surface-container": "#eeeef0",
        "error-container": "#ffdad6",
        "tertiary-container": "#cb8012",
        "on-secondary-container": "#27308a",
        "on-surface-variant": "#5b4039",
        "surface": "#f9f9fb",
        "on-tertiary-fixed-variant": "#673d00",
        "on-error-container": "#93000a",
        "on-surface": "#1a1c1d",
        "secondary-container": "#959efd",
        "surface-variant": "#e2e2e4",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#3b0900",
        "surface-tint": "#b02f00",
        "primary": "#b02f00",
        "on-primary-fixed-variant": "#862200",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e8e8ea",
        "surface-bright": "#f9f9fb",
        "on-tertiary-fixed": "#2b1700",
        "primary-fixed-dim": "#ffb5a0",
        "secondary-fixed-dim": "#bdc2ff",
        "tertiary": "#875200",
        "on-primary-container": "#541200",
        "on-secondary-fixed": "#000767",
        "outline": "#907067",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2f3132",
        "on-secondary-fixed-variant": "#343d96",
        "surface-dim": "#d9dadc",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#ffb866",
        "tertiary-fixed": "#ffddba",
        "inverse-on-surface": "#f0f0f2",
        "secondary-fixed": "#e0e0ff",
        "on-error": "#ffffff",
        "inverse-primary": "#ffb5a0",
        "background": "#f9f9fb",
        "on-tertiary-container": "#3f2400",
        "surface-container-low": "#f3f3f5",
        "primary-container": "#ff5722",
        "on-background": "#1a1c1d",
        "surface-container-highest": "#e2e2e4",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "24px",
        lg: "48px",
        sm: "12px",
        gutter: "24px",
        base: "8px",
        margin: "32px",
        xl: "80px",
        xs: "4px",
      },
      fontFamily: {
        "headline-sm": ["Epilogue", "sans-serif"],
        "display-lg": ["Epilogue", "sans-serif"],
        "label-sm": ["Work Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Epilogue", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Work Sans", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1.4", letterSpacing: "0.04em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
